# Generated by Django 4.0 on 2021-12-27 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('parent_area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiservice.area')),
            ],
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('parent_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiservice.area')),
            ],
        ),
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('uid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('doors', models.ManyToManyField(to='apiservice.Door')),
            ],
        ),
    ]
