# Generated by Django 4.0 on 2021-12-27 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiservice', '0002_area_child_area_ids'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessrule',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='uid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='door',
            old_name='uid',
            new_name='id',
        ),
    ]
